// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePosition = "sys_position"

// Position 系统岗位表
type Position struct {
	ID           int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:主键ID|Primary key" json:"id"`                     // 主键ID|Primary key
	DepartmentID *int64         `gorm:"column:department_id;type:bigint unsigned;comment:部门ID|Department ID" json:"department_id"`                           // 部门ID|Department ID
	Name         string         `gorm:"column:name;type:varchar(64);not null;comment:岗位名称|Position name" json:"name"`                                        // 岗位名称|Position name
	Code         string         `gorm:"column:code;type:varchar(64);not null;comment:岗位编码|Position code" json:"code"`                                        // 岗位编码|Position code
	Sort         int64          `gorm:"column:sort;type:int unsigned;not null;comment:排序|Sort" json:"sort"`                                                  // 排序|Sort
	Status       *int64         `gorm:"column:status;type:tinyint unsigned;not null;default:1;comment:状态 1:启用 2:禁用|Status 1:Enable 2:Disable" json:"status"` // 状态 1:启用 2:禁用|Status 1:Enable 2:Disable
	Remark       *string        `gorm:"column:remark;type:varchar(255);comment:备注|Remark" json:"remark"`                                                     // 备注|Remark
	CreatedAt    *time.Time     `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间|Created Time" json:"created_at"`      // 创建时间|Created Time
	UpdatedAt    *time.Time     `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间|Updated Time" json:"updated_at"`      // 更新时间|Updated Time
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间|Deleted Time" json:"deleted_at"`                                         // 删除时间|Deleted Time
	Department   *Department    `gorm:"foreignKey:DepartmentID;references:ID" json:"department"`
}

// TableName Position's table name
func (*Position) TableName() string {
	return TableNamePosition
}
