// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "sys_user"

// User 系统用户表
type User struct {
	ID           int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:主键ID|Primary key" json:"id"`                     // 主键ID|Primary key
	UUID         string         `gorm:"column:uuid;type:char(36);not null;comment:唯一标识符|UUID" json:"uuid"`                                                   // 唯一标识符|UUID
	Username     string         `gorm:"column:username;type:varchar(32);not null;comment:用户名|Username" json:"username"`                                      // 用户名|Username
	Password     string         `gorm:"column:password;type:varchar(32);not null;comment:密码|Password" json:"password"`                                       // 密码|Password
	Salt         string         `gorm:"column:salt;type:varchar(10);not null;comment:盐值|Salt" json:"salt"`                                                   // 盐值|Salt
	Name         string         `gorm:"column:name;type:varchar(32);not null;comment:姓名|Name" json:"name"`                                                   // 姓名|Name
	Nickname     *string        `gorm:"column:nickname;type:varchar(64);comment:昵称|Nickname" json:"nickname"`                                                // 昵称|Nickname
	Email        *string        `gorm:"column:email;type:varchar(64);comment:邮箱|Email" json:"email"`                                                         // 邮箱|Email
	Mobile       *string        `gorm:"column:mobile;type:varchar(11);comment:手机号|Mobile" json:"mobile"`                                                     // 手机号|Mobile
	Avatar       *string        `gorm:"column:avatar;type:varchar(255);comment:头像|Avatar" json:"avatar"`                                                     // 头像|Avatar
	Status       *int64         `gorm:"column:status;type:tinyint unsigned;not null;default:1;comment:状态 1:启用 2:禁用|Status 1:Enable 2:Disable" json:"status"` // 状态 1:启用 2:禁用|Status 1:Enable 2:Disable
	Remark       *string        `gorm:"column:remark;type:varchar(255);comment:备注|Remark" json:"remark"`                                                     // 备注|Remark
	HomePath     *string        `gorm:"column:home_path;type:varchar(128);not null;default:/dashboard;comment:首页路径|Home Path" json:"home_path"`              // 首页路径|Home Path
	DepartmentID *int64         `gorm:"column:department_id;type:bigint unsigned;comment:部门ID|Department ID" json:"department_id"`                           // 部门ID|Department ID
	PositionID   *int64         `gorm:"column:position_id;type:bigint unsigned;comment:岗位ID|Position ID" json:"position_id"`                                 // 岗位ID|Position ID
	LastLoginAt  *time.Time     `gorm:"column:last_login_at;type:datetime;comment:最后登录时间|Last Login Time" json:"last_login_at"`                              // 最后登录时间|Last Login Time
	LastLoginIP  *string        `gorm:"column:last_login_ip;type:varchar(50);comment:最后登录IP|Last Login IP" json:"last_login_ip"`                             // 最后登录IP|Last Login IP
	CreatedAt    *time.Time     `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间|Created Time" json:"created_at"`      // 创建时间|Created Time
	UpdatedAt    *time.Time     `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间|Updated Time" json:"updated_at"`      // 更新时间|Updated Time
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间|Deleted Time" json:"deleted_at"`                                         // 删除时间|Deleted Time
	Department   *Department    `gorm:"foreignKey:DepartmentID;references:ID" json:"department"`
	Position     *Position      `gorm:"foreignKey:PositionID;references:ID" json:"position"`
	Roles        []*Role        `gorm:"many2many:sys_user_role;foreignKey:ID;joinForeignKey:UserID;references:ID;joinReferences:RoleID" json:"roles"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
