// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameMenu = "sys_menu"

// Menu 系统菜单表
type Menu struct {
	ID                 int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:主键ID|Primary key" json:"id"`                                                           // 主键ID|Primary key
	ParentID           *int64         `gorm:"column:parent_id;type:bigint unsigned;comment:父菜单ID|Parent menu ID" json:"parent_id"`                                                                       // 父菜单ID|Parent menu ID
	Title              string         `gorm:"column:title;type:varchar(50);not null;comment:菜单标题|Menu title" json:"title"`                                                                               // 菜单标题|Menu title
	Name               string         `gorm:"column:name;type:varchar(50);not null;comment:菜单名称|Menu name" json:"name"`                                                                                  // 菜单名称|Menu name
	Path               *string        `gorm:"column:path;type:varchar(128);comment:菜单路径|Menu path" json:"path"`                                                                                          // 菜单路径|Menu path
	Component          *string        `gorm:"column:component;type:varchar(128);comment:组件路径|Component path" json:"component"`                                                                           // 组件路径|Component path
	Redirect           *string        `gorm:"column:redirect;type:varchar(128);comment:重定向|Redirect" json:"redirect"`                                                                                    // 重定向|Redirect
	Icon               *string        `gorm:"column:icon;type:varchar(50);comment:图标|Icon" json:"icon"`                                                                                                  // 图标|Icon
	Type               int64          `gorm:"column:type;type:tinyint unsigned;not null;comment:菜单类型 0:目录 1:菜单 2:按钮|Menu type 0:Directory 1:Menu 2:Button" json:"type"`                                  // 菜单类型 0:目录 1:菜单 2:按钮|Menu type 0:Directory 1:Menu 2:Button
	Permission         *string        `gorm:"column:permission;type:varchar(128);comment:权限标识|Permission" json:"permission"`                                                                             // 权限标识|Permission
	Sort               int64          `gorm:"column:sort;type:int unsigned;not null;comment:排序|Sort" json:"sort"`                                                                                        // 排序|Sort
	IsHidden           *int64         `gorm:"column:is_hidden;type:tinyint(1);not null;default:2;comment:是否隐藏 1:隐藏 2:显示|Is hidden 1:Hide 2:Show" json:"is_hidden"`                                       // 是否隐藏 1:隐藏 2:显示|Is hidden 1:Hide 2:Show
	IsCache            *int64         `gorm:"column:is_cache;type:tinyint(1);not null;default:2;comment:是否缓存 1:缓存 2:不缓存|Is cache 1:Yes 2:No" json:"is_cache"`                                            // 是否缓存 1:缓存 2:不缓存|Is cache 1:Yes 2:No
	IsAffix            *int64         `gorm:"column:is_affix;type:tinyint(1);not null;default:2;comment:是否固定 1:固定 2:不固定|Is affix 1:Yes 2:No" json:"is_affix"`                                            // 是否固定 1:固定 2:不固定|Is affix 1:Yes 2:No
	Trans              *string        `gorm:"column:trans;type:varchar(100);comment:多语言翻译|Translation" json:"trans"`                                                                                     // 多语言翻译|Translation
	Level              *int64         `gorm:"column:level;type:int unsigned;not null;default:1;comment:菜单层级|Menu level" json:"level"`                                                                    // 菜单层级|Menu level
	HideBreadcrumb     *int64         `gorm:"column:hide_breadcrumb;type:tinyint(1);not null;default:2;comment:是否隐藏面包屑 1:隐藏 2:显示|Hide breadcrumb 1:Yes 2:No" json:"hide_breadcrumb"`                     // 是否隐藏面包屑 1:隐藏 2:显示|Hide breadcrumb 1:Yes 2:No
	HideTab            *int64         `gorm:"column:hide_tab;type:tinyint(1);not null;default:2;comment:是否隐藏标签页 1:隐藏 2:显示|Hide tab 1:Yes 2:No" json:"hide_tab"`                                          // 是否隐藏标签页 1:隐藏 2:显示|Hide tab 1:Yes 2:No
	FrameSrc           *string        `gorm:"column:frame_src;type:varchar(255);comment:内嵌iframe地址|Frame source" json:"frame_src"`                                                                       // 内嵌iframe地址|Frame source
	CarryParam         *int64         `gorm:"column:carry_param;type:tinyint(1);not null;default:2;comment:是否携带参数 1:是 2:否|Carry param 1:Yes 2:No" json:"carry_param"`                                    // 是否携带参数 1:是 2:否|Carry param 1:Yes 2:No
	HideChildrenInMenu *int64         `gorm:"column:hide_children_in_menu;type:tinyint(1);not null;default:2;comment:是否在菜单中隐藏子节点 1:是 2:否|Hide children in menu 1:Yes 2:No" json:"hide_children_in_menu"` // 是否在菜单中隐藏子节点 1:是 2:否|Hide children in menu 1:Yes 2:No
	DynamicLevel       *int64         `gorm:"column:dynamic_level;type:int unsigned;default:20;comment:动态路由层级|Dynamic route level" json:"dynamic_level"`                                                 // 动态路由层级|Dynamic route level
	RealPath           *string        `gorm:"column:real_path;type:varchar(255);comment:真实路径|Real path" json:"real_path"`                                                                                // 真实路径|Real path
	Status             *int64         `gorm:"column:status;type:tinyint unsigned;not null;default:1;comment:状态 1:启用 2:禁用|Status 1:Enable 2:Disable" json:"status"`                                       // 状态 1:启用 2:禁用|Status 1:Enable 2:Disable
	CreatedAt          *time.Time     `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间|Created Time" json:"created_at"`                                            // 创建时间|Created Time
	UpdatedAt          *time.Time     `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间|Updated Time" json:"updated_at"`                                            // 更新时间|Updated Time
	DeletedAt          gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间|Deleted Time" json:"deleted_at"`                                                                               // 删除时间|Deleted Time
	Parent             *Menu          `gorm:"foreignKey:ParentID;references:ID" json:"parent"`
	Children           []*Menu        `gorm:"foreignKey:ParentID;references:ID" json:"children"`
}

// TableName Menu's table name
func (*Menu) TableName() string {
	return TableNameMenu
}
