// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRole = "sys_role"

// Role 系统角色表
type Role struct {
	ID            int64          `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:主键ID|Primary key" json:"id"`                        // 主键ID|Primary key
	Name          string         `gorm:"column:name;type:varchar(50);not null;comment:角色名称|Role name" json:"name"`                                               // 角色名称|Role name
	Code          string         `gorm:"column:code;type:varchar(50);not null;comment:角色编码|Role code" json:"code"`                                               // 角色编码|Role code
	DefaultRouter *string        `gorm:"column:default_router;type:varchar(128);not null;default:/dashboard;comment:默认的路由|Default router" json:"default_router"` // 默认的路由|Default router
	Status        *int64         `gorm:"column:status;type:tinyint unsigned;not null;default:1;comment:状态 1:启用 2:禁用|Status 1:Enable 2:Disable" json:"status"`    // 状态 1:启用 2:禁用|Status 1:Enable 2:Disable
	Remark        *string        `gorm:"column:remark;type:varchar(255);comment:备注|Remark" json:"remark"`                                                        // 备注|Remark
	Sort          int64          `gorm:"column:sort;type:int unsigned;not null;comment:排序|Sort" json:"sort"`                                                     // 排序|Sort
	CreatedAt     *time.Time     `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间|Created Time" json:"created_at"`         // 创建时间|Created Time
	UpdatedAt     *time.Time     `gorm:"column:updated_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:更新时间|Updated Time" json:"updated_at"`         // 更新时间|Updated Time
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;type:datetime;comment:删除时间|Deleted Time" json:"deleted_at"`                                            // 删除时间|Deleted Time
	Users         []*User        `gorm:"many2many:sys_user_role;foreignKey:ID;joinForeignKey:RoleID;references:ID;joinReferences:UserID" json:"users"`
}

// TableName Role's table name
func (*Role) TableName() string {
	return TableNameRole
}
