// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"simple/internal/types/entity"
)

func newMenu(db *gorm.DB, opts ...gen.DOOption) menu {
	_menu := menu{}

	_menu.menuDo.UseDB(db, opts...)
	_menu.menuDo.UseModel(&entity.Menu{})

	tableName := _menu.menuDo.TableName()
	_menu.ALL = field.NewAsterisk(tableName)
	_menu.ID = field.NewInt64(tableName, "id")
	_menu.ParentID = field.NewInt64(tableName, "parent_id")
	_menu.Title = field.NewString(tableName, "title")
	_menu.Name = field.NewString(tableName, "name")
	_menu.Path = field.NewString(tableName, "path")
	_menu.Component = field.NewString(tableName, "component")
	_menu.Redirect = field.NewString(tableName, "redirect")
	_menu.Icon = field.NewString(tableName, "icon")
	_menu.Type = field.NewInt64(tableName, "type")
	_menu.Permission = field.NewString(tableName, "permission")
	_menu.Sort = field.NewInt64(tableName, "sort")
	_menu.IsHidden = field.NewInt64(tableName, "is_hidden")
	_menu.IsCache = field.NewInt64(tableName, "is_cache")
	_menu.IsAffix = field.NewInt64(tableName, "is_affix")
	_menu.Trans = field.NewString(tableName, "trans")
	_menu.Level = field.NewInt64(tableName, "level")
	_menu.HideBreadcrumb = field.NewInt64(tableName, "hide_breadcrumb")
	_menu.HideTab = field.NewInt64(tableName, "hide_tab")
	_menu.FrameSrc = field.NewString(tableName, "frame_src")
	_menu.CarryParam = field.NewInt64(tableName, "carry_param")
	_menu.HideChildrenInMenu = field.NewInt64(tableName, "hide_children_in_menu")
	_menu.DynamicLevel = field.NewInt64(tableName, "dynamic_level")
	_menu.RealPath = field.NewString(tableName, "real_path")
	_menu.Status = field.NewInt64(tableName, "status")
	_menu.CreatedAt = field.NewTime(tableName, "created_at")
	_menu.UpdatedAt = field.NewTime(tableName, "updated_at")
	_menu.DeletedAt = field.NewField(tableName, "deleted_at")

	_menu.fillFieldMap()

	return _menu
}

// menu 系统菜单表
type menu struct {
	menuDo

	ALL                field.Asterisk
	ID                 field.Int64  // 主键ID|Primary key
	ParentID           field.Int64  // 父菜单ID|Parent menu ID
	Title              field.String // 菜单标题|Menu title
	Name               field.String // 菜单名称|Menu name
	Path               field.String // 菜单路径|Menu path
	Component          field.String // 组件路径|Component path
	Redirect           field.String // 重定向|Redirect
	Icon               field.String // 图标|Icon
	Type               field.Int64  // 菜单类型 0:目录 1:菜单 2:按钮|Menu type 0:Directory 1:Menu 2:Button
	Permission         field.String // 权限标识|Permission
	Sort               field.Int64  // 排序|Sort
	IsHidden           field.Int64  // 是否隐藏 1:隐藏 2:显示|Is hidden 1:Hide 2:Show
	IsCache            field.Int64  // 是否缓存 1:缓存 2:不缓存|Is cache 1:Yes 2:No
	IsAffix            field.Int64  // 是否固定 1:固定 2:不固定|Is affix 1:Yes 2:No
	Trans              field.String // 多语言翻译|Translation
	Level              field.Int64  // 菜单层级|Menu level
	HideBreadcrumb     field.Int64  // 是否隐藏面包屑 1:隐藏 2:显示|Hide breadcrumb 1:Yes 2:No
	HideTab            field.Int64  // 是否隐藏标签页 1:隐藏 2:显示|Hide tab 1:Yes 2:No
	FrameSrc           field.String // 内嵌iframe地址|Frame source
	CarryParam         field.Int64  // 是否携带参数 1:是 2:否|Carry param 1:Yes 2:No
	HideChildrenInMenu field.Int64  // 是否在菜单中隐藏子节点 1:是 2:否|Hide children in menu 1:Yes 2:No
	DynamicLevel       field.Int64  // 动态路由层级|Dynamic route level
	RealPath           field.String // 真实路径|Real path
	Status             field.Int64  // 状态 1:启用 2:禁用|Status 1:Enable 2:Disable
	CreatedAt          field.Time   // 创建时间|Created Time
	UpdatedAt          field.Time   // 更新时间|Updated Time
	DeletedAt          field.Field  // 删除时间|Deleted Time

	fieldMap map[string]field.Expr
}

func (m menu) Table(newTableName string) *menu {
	m.menuDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m menu) As(alias string) *menu {
	m.menuDo.DO = *(m.menuDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *menu) updateTableName(table string) *menu {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt64(table, "id")
	m.ParentID = field.NewInt64(table, "parent_id")
	m.Title = field.NewString(table, "title")
	m.Name = field.NewString(table, "name")
	m.Path = field.NewString(table, "path")
	m.Component = field.NewString(table, "component")
	m.Redirect = field.NewString(table, "redirect")
	m.Icon = field.NewString(table, "icon")
	m.Type = field.NewInt64(table, "type")
	m.Permission = field.NewString(table, "permission")
	m.Sort = field.NewInt64(table, "sort")
	m.IsHidden = field.NewInt64(table, "is_hidden")
	m.IsCache = field.NewInt64(table, "is_cache")
	m.IsAffix = field.NewInt64(table, "is_affix")
	m.Trans = field.NewString(table, "trans")
	m.Level = field.NewInt64(table, "level")
	m.HideBreadcrumb = field.NewInt64(table, "hide_breadcrumb")
	m.HideTab = field.NewInt64(table, "hide_tab")
	m.FrameSrc = field.NewString(table, "frame_src")
	m.CarryParam = field.NewInt64(table, "carry_param")
	m.HideChildrenInMenu = field.NewInt64(table, "hide_children_in_menu")
	m.DynamicLevel = field.NewInt64(table, "dynamic_level")
	m.RealPath = field.NewString(table, "real_path")
	m.Status = field.NewInt64(table, "status")
	m.CreatedAt = field.NewTime(table, "created_at")
	m.UpdatedAt = field.NewTime(table, "updated_at")
	m.DeletedAt = field.NewField(table, "deleted_at")

	m.fillFieldMap()

	return m
}

func (m *menu) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *menu) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 29)
	m.fieldMap["id"] = m.ID
	m.fieldMap["parent_id"] = m.ParentID
	m.fieldMap["title"] = m.Title
	m.fieldMap["name"] = m.Name
	m.fieldMap["path"] = m.Path
	m.fieldMap["component"] = m.Component
	m.fieldMap["redirect"] = m.Redirect
	m.fieldMap["icon"] = m.Icon
	m.fieldMap["type"] = m.Type
	m.fieldMap["permission"] = m.Permission
	m.fieldMap["sort"] = m.Sort
	m.fieldMap["is_hidden"] = m.IsHidden
	m.fieldMap["is_cache"] = m.IsCache
	m.fieldMap["is_affix"] = m.IsAffix
	m.fieldMap["trans"] = m.Trans
	m.fieldMap["level"] = m.Level
	m.fieldMap["hide_breadcrumb"] = m.HideBreadcrumb
	m.fieldMap["hide_tab"] = m.HideTab
	m.fieldMap["frame_src"] = m.FrameSrc
	m.fieldMap["carry_param"] = m.CarryParam
	m.fieldMap["hide_children_in_menu"] = m.HideChildrenInMenu
	m.fieldMap["dynamic_level"] = m.DynamicLevel
	m.fieldMap["real_path"] = m.RealPath
	m.fieldMap["status"] = m.Status
	m.fieldMap["created_at"] = m.CreatedAt
	m.fieldMap["updated_at"] = m.UpdatedAt
	m.fieldMap["deleted_at"] = m.DeletedAt

}

func (m menu) clone(db *gorm.DB) menu {
	m.menuDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m menu) replaceDB(db *gorm.DB) menu {
	m.menuDo.ReplaceDB(db)
	return m
}

type menuDo struct{ gen.DO }

func (m menuDo) Debug() *menuDo {
	return m.withDO(m.DO.Debug())
}

func (m menuDo) WithContext(ctx context.Context) *menuDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m menuDo) ReadDB() *menuDo {
	return m.Clauses(dbresolver.Read)
}

func (m menuDo) WriteDB() *menuDo {
	return m.Clauses(dbresolver.Write)
}

func (m menuDo) Session(config *gorm.Session) *menuDo {
	return m.withDO(m.DO.Session(config))
}

func (m menuDo) Clauses(conds ...clause.Expression) *menuDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m menuDo) Returning(value interface{}, columns ...string) *menuDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m menuDo) Not(conds ...gen.Condition) *menuDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m menuDo) Or(conds ...gen.Condition) *menuDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m menuDo) Select(conds ...field.Expr) *menuDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m menuDo) Where(conds ...gen.Condition) *menuDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m menuDo) Order(conds ...field.Expr) *menuDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m menuDo) Distinct(cols ...field.Expr) *menuDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m menuDo) Omit(cols ...field.Expr) *menuDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m menuDo) Join(table schema.Tabler, on ...field.Expr) *menuDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m menuDo) LeftJoin(table schema.Tabler, on ...field.Expr) *menuDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m menuDo) RightJoin(table schema.Tabler, on ...field.Expr) *menuDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m menuDo) Group(cols ...field.Expr) *menuDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m menuDo) Having(conds ...gen.Condition) *menuDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m menuDo) Limit(limit int) *menuDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m menuDo) Offset(offset int) *menuDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m menuDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *menuDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m menuDo) Unscoped() *menuDo {
	return m.withDO(m.DO.Unscoped())
}

func (m menuDo) Create(values ...*entity.Menu) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m menuDo) CreateInBatches(values []*entity.Menu, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m menuDo) Save(values ...*entity.Menu) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m menuDo) First() (*entity.Menu, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Menu), nil
	}
}

func (m menuDo) Take() (*entity.Menu, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Menu), nil
	}
}

func (m menuDo) Last() (*entity.Menu, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Menu), nil
	}
}

func (m menuDo) Find() ([]*entity.Menu, error) {
	result, err := m.DO.Find()
	return result.([]*entity.Menu), err
}

func (m menuDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*entity.Menu, err error) {
	buf := make([]*entity.Menu, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m menuDo) FindInBatches(result *[]*entity.Menu, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m menuDo) Attrs(attrs ...field.AssignExpr) *menuDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m menuDo) Assign(attrs ...field.AssignExpr) *menuDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m menuDo) Joins(fields ...field.RelationField) *menuDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m menuDo) Preload(fields ...field.RelationField) *menuDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m menuDo) FirstOrInit() (*entity.Menu, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Menu), nil
	}
}

func (m menuDo) FirstOrCreate() (*entity.Menu, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*entity.Menu), nil
	}
}

func (m menuDo) FindByPage(offset int, limit int) (result []*entity.Menu, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m menuDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m menuDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m menuDo) Delete(models ...*entity.Menu) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *menuDo) withDO(do gen.Dao) *menuDo {
	m.DO = *do.(*gen.DO)
	return m
}
